patcher: check if target directory exists

diff --git a/hooks/discord/patcher b/hooks/discord/patcher
--- a/hooks/discord/patcher
+++ b/hooks/discord/patcher
@@ -2,7 +2,7 @@
 # hooks/discord/patcher
 #
 # Patches Discord electron app to retrieves internal notification state
-# and send it to unread-bell through a FIFO.
+# and send it to unread-bell through a websocket.
 # Does nothing if the app is already patched.
 #
 # Parameters:
@@ -10,6 +10,11 @@
 
 if [[ -z "$1" ]]; then
     >&2 echo "Missing parameter: Discord config directory.";
+    exit 1
+fi
+
+if [[ ! -d "$1" ]]; then
+    >&2 echo "Invalid parameter: directory does not exist.";
     exit 1
 fi
 
